import React, { createContext, useContext, useState, useCallback } from "react";

export type Language = "ko" | "ja" | "zh" | "en" | "th" | "vi" | "id";

export const LANGUAGES: { code: Language; label: string; nativeLabel: string; flag: string }[] = [
  { code: "ko", label: "Korean", nativeLabel: "한국어", flag: "🇰🇷" },
  { code: "ja", label: "Japanese", nativeLabel: "日本語", flag: "🇯🇵" },
  { code: "zh", label: "Chinese", nativeLabel: "中文", flag: "🇨🇳" },
  { code: "en", label: "English", nativeLabel: "English", flag: "🇺🇸" },
  { code: "th", label: "Thai", nativeLabel: "ไทย", flag: "🇹🇭" },
  { code: "vi", label: "Vietnamese", nativeLabel: "Tiếng Việt", flag: "🇻🇳" },
  { code: "id", label: "Indonesian", nativeLabel: "Bahasa Indonesia", flag: "🇮🇩" },
];

// UI translations - 새 언어 추가 시 아래에 추가하면 됨
const translations: Record<Language, Record<string, string>> = {
  ko: {
    "nav.home": "홈",
    "nav.community": "커뮤니티",
    "nav.guide": "로컬 가이드",
    "nav.map": "지도",
    "nav.login": "로그인",
    "nav.logout": "로그아웃",
    "nav.profile": "프로필",
    "nav.tagline": "부산 다국어 관광 커뮤니티",
    "hero.title": "부산을 함께 발견하세요",
    "hero.subtitle": "전 세계 여행자와 현지인이 연결되는 공간",
    "hero.description": "AI 번역으로 언어 장벽 없이 부산의 숨겨진 보석을 탐험하고, 여행 경험을 나누세요.",
    "hero.cta.community": "커뮤니티 참여하기",
    "hero.cta.guide": "로컬 가이드 보기",
    "features.title": "BusanConnect를 선택해야 하는 이유",
    "features.translation.title": "AI 실시간 번역",
    "features.translation.desc": "LLM 기반 고품질 번역으로 언어 장벽 없이 소통하세요",
    "features.community.title": "글로벌 커뮤니티",
    "features.community.desc": "한국어, 일본어, 중국어, 영어로 여행 경험을 공유하세요",
    "features.guide.title": "로컬 가이드",
    "features.guide.desc": "현지인이 추천하는 부산의 숨겨진 명소와 맛집을 발견하세요",
    "features.map.title": "인터랙티브 지도",
    "features.map.desc": "Google Maps로 부산의 명소를 시각적으로 탐험하세요",
    "community.title": "커뮤니티",
    "community.subtitle": "여행자들의 이야기",
    "community.write": "글 작성",
    "community.category.all": "전체",
    "community.category.review": "여행 후기",
    "community.category.question": "질문",
    "community.category.tip": "여행 팁",
    "community.category.general": "일반",
    "community.empty": "아직 글이 없습니다. 첫 번째로 작성해보세요!",
    "community.login_required": "글을 작성하려면 로그인이 필요합니다",
    "community.views": "조회",
    "community.comments": "댓글",
    "post.title": "제목",
    "post.content": "내용",
    "post.category": "카테고리",
    "post.language": "작성 언어",
    "post.submit": "등록",
    "post.cancel": "취소",
    "post.translate": "번역",
    "post.translating": "번역 중...",
    "post.translated": "번역됨",
    "post.original": "원문 보기",
    "post.comment.placeholder": "댓글을 작성하세요...",
    "post.comment.submit": "댓글",
    "post.comment.login": "댓글을 작성하려면 로그인이 필요합니다",
    "guide.title": "로컬 가이드",
    "guide.subtitle": "부산의 숨겨진 보석을 발견하세요",
    "guide.category.all": "전체",
    "guide.category.attraction": "명소",
    "guide.category.restaurant": "맛집",
    "guide.category.accommodation": "숙소",
    "guide.category.shopping": "쇼핑",
    "guide.category.culture": "문화",
    "guide.map_view": "지도에서 보기",
    "map.title": "부산 명소 지도",
    "map.subtitle": "지도에서 부산의 명소를 탐험하세요",
    "profile.title": "내 프로필",
    "profile.nickname": "닉네임",
    "profile.preferred_language": "선호 언어",
    "profile.bio": "소개",
    "profile.my_posts": "내 글",
    "profile.save": "저장",
    "profile.saved": "저장됨",
    "common.loading": "로딩 중...",
    "common.error": "오류가 발생했습니다",
    "common.back": "뒤로",
    "common.more": "더 보기",
    "common.close": "닫기",
    "common.by": "작성자",
    "common.ago": "전",
    "common.login_to_continue": "계속하려면 로그인하세요",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.community": "コミュニティ",
    "nav.guide": "ローカルガイド",
    "nav.map": "地図",
    "nav.login": "ログイン",
    "nav.logout": "ログアウト",
    "nav.profile": "プロフィール",
    "nav.tagline": "釜山多言語旅行コミュニティ",
    "hero.title": "釜山を一緒に発見しましょう",
    "hero.subtitle": "世界中の旅行者と地元の人が繋がる場所",
    "hero.description": "AI翻訳で言語の壁なく釜山の隠れた宝石を探索し、旅行体験をシェアしましょう。",
    "hero.cta.community": "コミュニティに参加",
    "hero.cta.guide": "ローカルガイドを見る",
    "features.title": "BusanConnectを選ぶ理由",
    "features.translation.title": "AIリアルタイム翻訳",
    "features.translation.desc": "LLMベースの高品質翻訳で言語の壁なくコミュニケーション",
    "features.community.title": "グローバルコミュニティ",
    "features.community.desc": "韓国語、日本語、中国語、英語で旅行体験をシェア",
    "features.guide.title": "ローカルガイド",
    "features.guide.desc": "地元の人がおすすめする釜山の隠れた名所とレストランを発見",
    "features.map.title": "インタラクティブマップ",
    "features.map.desc": "Google Mapsで釜山の観光地を視覚的に探索",
    "community.title": "コミュニティ",
    "community.subtitle": "旅行者のストーリー",
    "community.write": "投稿を作成",
    "community.category.all": "すべて",
    "community.category.review": "旅行レビュー",
    "community.category.question": "質問",
    "community.category.tip": "旅行ヒント",
    "community.category.general": "一般",
    "community.empty": "まだ投稿がありません。最初に投稿してみてください！",
    "community.login_required": "投稿するにはログインが必要です",
    "community.views": "ビュー",
    "community.comments": "コメント",
    "post.title": "タイトル",
    "post.content": "コンテンツ",
    "post.category": "カテゴリー",
    "post.language": "執筆言語",
    "post.submit": "投稿",
    "post.cancel": "キャンセル",
    "post.translate": "翻訳",
    "post.translating": "翻訳中...",
    "post.translated": "翻訳済み",
    "post.original": "原文を表示",
    "post.comment.placeholder": "コメントを書く...",
    "post.comment.submit": "コメント",
    "post.comment.login": "コメントするにはログインが必要です",
    "guide.title": "ローカルガイド",
    "guide.subtitle": "釜山の隠れた宝石を発見",
    "guide.category.all": "すべて",
    "guide.category.attraction": "観光地",
    "guide.category.restaurant": "レストラン",
    "guide.category.accommodation": "宿泊施設",
    "guide.category.shopping": "ショッピング",
    "guide.category.culture": "文化",
    "guide.map_view": "地図で表示",
    "map.title": "釜山観光地マップ",
    "map.subtitle": "地図で釜山の観光地を探索",
    "profile.title": "マイプロフィール",
    "profile.nickname": "ニックネーム",
    "profile.preferred_language": "希望言語",
    "profile.bio": "自己紹介",
    "profile.my_posts": "マイ投稿",
    "profile.save": "保存",
    "profile.saved": "保存済み",
    "common.loading": "ロード中...",
    "common.error": "エラーが発生しました",
    "common.back": "戻る",
    "common.more": "もっと見る",
    "common.close": "閉じる",
    "common.by": "著者",
    "common.ago": "前",
    "common.login_to_continue": "続行するにはログイン",
  },
  zh: {
    "nav.home": "首页",
    "nav.community": "社区",
    "nav.guide": "本地指南",
    "nav.map": "地图",
    "nav.login": "登录",
    "nav.logout": "登出",
    "nav.profile": "个人资料",
    "nav.tagline": "釜山多语言旅游社区",
    "hero.title": "一起发现釜山",
    "hero.subtitle": "全球旅行者与当地人相连的地方",
    "hero.description": "通过AI翻译无语言障碍地探索釜山的隐藏宝石，分享您的旅行体验。",
    "hero.cta.community": "加入社区",
    "hero.cta.guide": "查看本地指南",
    "features.title": "为什么选择BusanConnect？",
    "features.translation.title": "AI实时翻译",
    "features.translation.desc": "使用基于LLM的高质量翻译进行无语言障碍沟通",
    "features.community.title": "全球社区",
    "features.community.desc": "用韩语、日语、中文和英文分享旅行体验",
    "features.guide.title": "本地指南",
    "features.guide.desc": "发现当地人推荐的釜山隐藏景点和餐厅",
    "features.map.title": "交互式地图",
    "features.map.desc": "使用Google地图直观探索釜山的景点",
    "community.title": "社区",
    "community.subtitle": "旅行者的故事",
    "community.write": "写帖子",
    "community.category.all": "全部",
    "community.category.review": "旅游评论",
    "community.category.question": "问题",
    "community.category.tip": "旅游提示",
    "community.category.general": "一般",
    "community.empty": "还没有帖子。成为第一个发布的人！",
    "community.login_required": "需要登录才能发布帖子",
    "community.views": "浏览",
    "community.comments": "评论",
    "post.title": "标题",
    "post.content": "内容",
    "post.category": "类别",
    "post.language": "写作语言",
    "post.submit": "发布",
    "post.cancel": "取消",
    "post.translate": "翻译",
    "post.translating": "翻译中...",
    "post.translated": "已翻译",
    "post.original": "查看原文",
    "post.comment.placeholder": "写评论...",
    "post.comment.submit": "评论",
    "post.comment.login": "需要登录才能评论",
    "guide.title": "本地指南",
    "guide.subtitle": "发现釜山的隐藏宝石",
    "guide.category.all": "全部",
    "guide.category.attraction": "景点",
    "guide.category.restaurant": "餐厅",
    "guide.category.accommodation": "住宿",
    "guide.category.shopping": "购物",
    "guide.category.culture": "文化",
    "guide.map_view": "在地图上查看",
    "map.title": "釜山景点地图",
    "map.subtitle": "在地图上探索釜山的景点",
    "profile.title": "我的资料",
    "profile.nickname": "昵称",
    "profile.preferred_language": "首选语言",
    "profile.bio": "个人简介",
    "profile.my_posts": "我的帖子",
    "profile.save": "保存",
    "profile.saved": "已保存",
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.back": "返回",
    "common.more": "查看更多",
    "common.close": "关闭",
    "common.by": "作者",
    "common.ago": "前",
    "common.login_to_continue": "请登录以继续",
  },
  en: {
    "nav.home": "Home",
    "nav.community": "Community",
    "nav.guide": "Local Guide",
    "nav.map": "Map",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.profile": "Profile",
    "nav.tagline": "Busan Multilingual Travel Community",
    "hero.title": "Discover Busan Together",
    "hero.subtitle": "Where global travelers and locals connect",
    "hero.description": "Explore Busan's hidden gems without language barriers through AI translation, and share your travel experiences.",
    "hero.cta.community": "Join Community",
    "hero.cta.guide": "View Local Guide",
    "features.title": "Why BusanConnect?",
    "features.translation.title": "AI Real-time Translation",
    "features.translation.desc": "Communicate without language barriers with LLM-based high-quality translation",
    "features.community.title": "Global Community",
    "features.community.desc": "Share travel experiences in Korean, Japanese, Chinese, and English",
    "features.guide.title": "Local Guide",
    "features.guide.desc": "Discover hidden spots and restaurants in Busan recommended by locals",
    "features.map.title": "Interactive Map",
    "features.map.desc": "Visually explore Busan's attractions with Google Maps",
    "community.title": "Community",
    "community.subtitle": "Stories from travelers",
    "community.write": "Write Post",
    "community.category.all": "All",
    "community.category.review": "Travel Review",
    "community.category.question": "Question",
    "community.category.tip": "Travel Tip",
    "community.category.general": "General",
    "community.empty": "No posts yet. Be the first to write one!",
    "community.login_required": "Login required to write posts",
    "community.views": "Views",
    "community.comments": "Comments",
    "post.title": "Title",
    "post.content": "Content",
    "post.category": "Category",
    "post.language": "Writing Language",
    "post.submit": "Post",
    "post.cancel": "Cancel",
    "post.translate": "Translate",
    "post.translating": "Translating...",
    "post.translated": "Translated",
    "post.original": "View Original",
    "post.comment.placeholder": "Write a comment...",
    "post.comment.submit": "Comment",
    "post.comment.login": "Login required to comment",
    "guide.title": "Local Guide",
    "guide.subtitle": "Discover Busan's hidden gems",
    "guide.category.all": "All",
    "guide.category.attraction": "Attractions",
    "guide.category.restaurant": "Restaurants",
    "guide.category.accommodation": "Accommodation",
    "guide.category.shopping": "Shopping",
    "guide.category.culture": "Culture",
    "guide.map_view": "View on Map",
    "map.title": "Busan Attractions Map",
    "map.subtitle": "Explore Busan's attractions on the map",
    "profile.title": "My Profile",
    "profile.nickname": "Nickname",
    "profile.preferred_language": "Preferred Language",
    "profile.bio": "Bio",
    "profile.my_posts": "My Posts",
    "profile.save": "Save",
    "profile.saved": "Saved",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.back": "Back",
    "common.more": "View More",
    "common.close": "Close",
    "common.by": "By",
    "common.ago": "ago",
    "common.login_to_continue": "Login to continue",
  },
  th: {
    "nav.home": "หน้าแรก",
    "nav.community": "ชุมชน",
    "nav.guide": "คู่มือท้องถิ่น",
    "nav.map": "แผนที่",
    "nav.login": "เข้าสู่ระบบ",
    "nav.logout": "ออกจากระบบ",
    "nav.profile": "โปรไฟล์",
    "nav.tagline": "ชุมชนท่องเที่ยวพหุภาษาของปูซาน",
    "hero.title": "ค้นพบปูซานด้วยกัน",
    "hero.subtitle": "ที่ที่นักท่องเที่ยวทั่วโลกและชาวท้องถิ่นเชื่อมต่อ",
    "hero.description": "สำรวจอัญมณีที่ซ่อนอยู่ของปูซานโดยไม่มีอุปสรรคด้านภาษาผ่านการแปลด้วย AI และแบ่งปันประสบการณ์การท่องเที่ยวของคุณ",
    "hero.cta.community": "เข้าร่วมชุมชน",
    "hero.cta.guide": "ดูคู่มือท้องถิ่น",
    "features.title": "ทำไมต้อง BusanConnect?",
    "features.translation.title": "การแปลแบบเรียลไทม์ของ AI",
    "features.translation.desc": "สื่อสารโดยไม่มีอุปสรรคด้านภาษาด้วยการแปลคุณภาพสูงที่ใช้ LLM",
    "features.community.title": "ชุมชนโลก",
    "features.community.desc": "แบ่งปันประสบการณ์การท่องเที่ยวในภาษาเกาหลี ญี่ปุ่น จีน และอังกฤษ",
    "features.guide.title": "คู่มือท้องถิ่น",
    "features.guide.desc": "ค้นพบสถานที่ที่ซ่อนอยู่และร้านอาหารในปูซานที่ชาวท้องถิ่นแนะนำ",
    "features.map.title": "แผนที่แบบโต้ตอบ",
    "features.map.desc": "สำรวจสถานที่ท่องเที่ยวของปูซานด้วยสายตาโดยใช้ Google Maps",
    "community.title": "ชุมชน",
    "community.subtitle": "เรื่องราวจากนักท่องเที่ยว",
    "community.write": "เขียนโพสต์",
    "community.category.all": "ทั้งหมด",
    "community.category.review": "รีวิวการท่องเที่ยว",
    "community.category.question": "คำถาม",
    "community.category.tip": "เคล็ดลับการท่องเที่ยว",
    "community.category.general": "ทั่วไป",
    "community.empty": "ยังไม่มีโพสต์ เป็นคนแรกที่เขียน!",
    "community.login_required": "ต้องเข้าสู่ระบบเพื่อเขียนโพสต์",
    "community.views": "มุมมอง",
    "community.comments": "ความเห็น",
    "post.title": "ชื่อเรื่อง",
    "post.content": "เนื้อหา",
    "post.category": "หมวดหมู่",
    "post.language": "ภาษาการเขียน",
    "post.submit": "โพสต์",
    "post.cancel": "ยกเลิก",
    "post.translate": "แปล",
    "post.translating": "กำลังแปล...",
    "post.translated": "แปลแล้ว",
    "post.original": "ดูต้นฉบับ",
    "post.comment.placeholder": "เขียนความเห็น...",
    "post.comment.submit": "ความเห็น",
    "post.comment.login": "ต้องเข้าสู่ระบบเพื่อแสดงความเห็น",
    "guide.title": "คู่มือท้องถิ่น",
    "guide.subtitle": "ค้นพบอัญมณีที่ซ่อนอยู่ของปูซาน",
    "guide.category.all": "ทั้งหมด",
    "guide.category.attraction": "สถานที่ท่องเที่ยว",
    "guide.category.restaurant": "ร้านอาหาร",
    "guide.category.accommodation": "ที่พัก",
    "guide.category.shopping": "การช้อปปิ้ง",
    "guide.category.culture": "วัฒนธรรม",
    "guide.map_view": "ดูบนแผนที่",
    "map.title": "แผนที่สถานที่ท่องเที่ยวของปูซาน",
    "map.subtitle": "สำรวจสถานที่ท่องเที่ยวของปูซานบนแผนที่",
    "profile.title": "โปรไฟล์ของฉัน",
    "profile.nickname": "ชื่อเล่น",
    "profile.preferred_language": "ภาษาที่ต้องการ",
    "profile.bio": "ชีวประวัติ",
    "profile.my_posts": "โพสต์ของฉัน",
    "profile.save": "บันทึก",
    "profile.saved": "บันทึกแล้ว",
    "common.loading": "กำลังโหลด...",
    "common.error": "เกิดข้อผิดพลาด",
    "common.back": "กลับ",
    "common.more": "ดูเพิ่มเติม",
    "common.close": "ปิด",
    "common.by": "โดย",
    "common.ago": "ที่แล้ว",
    "common.login_to_continue": "เข้าสู่ระบบเพื่อดำเนินการต่อ",
  },
  vi: {
    "nav.home": "Trang chủ",
    "nav.community": "Cộng đồng",
    "nav.guide": "Hướng dẫn địa phương",
    "nav.map": "Bản đồ",
    "nav.login": "Đăng nhập",
    "nav.logout": "Đăng xuất",
    "nav.profile": "Hồ sơ",
    "nav.tagline": "Cộng đồng du lịch đa ngôn ngữ Busan",
    "hero.title": "Khám phá Busan cùng nhau",
    "hero.subtitle": "Nơi các du khách toàn cầu và người dân địa phương kết nối",
    "hero.description": "Khám phá những viên ngọc ẩn của Busan mà không có rào cản ngôn ngữ thông qua dịch thuật AI và chia sẻ trải nghiệm du lịch của bạn.",
    "hero.cta.community": "Tham gia cộng đồng",
    "hero.cta.guide": "Xem hướng dẫn địa phương",
    "features.title": "Tại sao chọn BusanConnect?",
    "features.translation.title": "Dịch thuật AI theo thời gian thực",
    "features.translation.desc": "Giao tiếp mà không có rào cản ngôn ngữ với dịch thuật chất lượng cao dựa trên LLM",
    "features.community.title": "Cộng đồng toàn cầu",
    "features.community.desc": "Chia sẻ trải nghiệm du lịch bằng tiếng Hàn, Nhật, Trung Quốc và Anh",
    "features.guide.title": "Hướng dẫn địa phương",
    "features.guide.desc": "Khám phá những địa điểm ẩn và nhà hàng ở Busan được người dân địa phương giới thiệu",
    "features.map.title": "Bản đồ tương tác",
    "features.map.desc": "Khám phá trực quan các điểm tham quan của Busan bằng Google Maps",
    "community.title": "Cộng đồng",
    "community.subtitle": "Câu chuyện từ những du khách",
    "community.write": "Viết bài",
    "community.category.all": "Tất cả",
    "community.category.review": "Đánh giá du lịch",
    "community.category.question": "Câu hỏi",
    "community.category.tip": "Mẹo du lịch",
    "community.category.general": "Chung",
    "community.empty": "Chưa có bài viết. Hãy là người đầu tiên viết!",
    "community.login_required": "Cần đăng nhập để viết bài",
    "community.views": "Lượt xem",
    "community.comments": "Bình luận",
    "post.title": "Tiêu đề",
    "post.content": "Nội dung",
    "post.category": "Danh mục",
    "post.language": "Ngôn ngữ viết",
    "post.submit": "Đăng",
    "post.cancel": "Hủy",
    "post.translate": "Dịch",
    "post.translating": "Đang dịch...",
    "post.translated": "Đã dịch",
    "post.original": "Xem bản gốc",
    "post.comment.placeholder": "Viết bình luận...",
    "post.comment.submit": "Bình luận",
    "post.comment.login": "Cần đăng nhập để bình luận",
    "guide.title": "Hướng dẫn địa phương",
    "guide.subtitle": "Khám phá những viên ngọc ẩn của Busan",
    "guide.category.all": "Tất cả",
    "guide.category.attraction": "Điểm tham quan",
    "guide.category.restaurant": "Nhà hàng",
    "guide.category.accommodation": "Chỗ ở",
    "guide.category.shopping": "Mua sắm",
    "guide.category.culture": "Văn hóa",
    "guide.map_view": "Xem trên bản đồ",
    "map.title": "Bản đồ điểm tham quan Busan",
    "map.subtitle": "Khám phá các điểm tham quan của Busan trên bản đồ",
    "profile.title": "Hồ sơ của tôi",
    "profile.nickname": "Biệt danh",
    "profile.preferred_language": "Ngôn ngữ ưa thích",
    "profile.bio": "Tiểu sử",
    "profile.my_posts": "Bài viết của tôi",
    "profile.save": "Lưu",
    "profile.saved": "Đã lưu",
    "common.loading": "Đang tải...",
    "common.error": "Đã xảy ra lỗi",
    "common.back": "Quay lại",
    "common.more": "Xem thêm",
    "common.close": "Đóng",
    "common.by": "Bởi",
    "common.ago": "trước",
    "common.login_to_continue": "Đăng nhập để tiếp tục",
  },
  id: {
    "nav.home": "Beranda",
    "nav.community": "Komunitas",
    "nav.guide": "Panduan Lokal",
    "nav.map": "Peta",
    "nav.login": "Masuk",
    "nav.logout": "Keluar",
    "nav.profile": "Profil",
    "nav.tagline": "Komunitas Pariwisata Multibahasa Busan",
    "hero.title": "Temukan Busan Bersama",
    "hero.subtitle": "Tempat di mana wisatawan global dan penduduk lokal terhubung",
    "hero.description": "Jelajahi permata tersembunyi Busan tanpa hambatan bahasa melalui terjemahan AI dan bagikan pengalaman perjalanan Anda.",
    "hero.cta.community": "Bergabung dengan Komunitas",
    "hero.cta.guide": "Lihat Panduan Lokal",
    "features.title": "Mengapa BusanConnect?",
    "features.translation.title": "Terjemahan AI Waktu Nyata",
    "features.translation.desc": "Berkomunikasi tanpa hambatan bahasa dengan terjemahan berkualitas tinggi berbasis LLM",
    "features.community.title": "Komunitas Global",
    "features.community.desc": "Bagikan pengalaman perjalanan dalam bahasa Korea, Jepang, Cina, dan Inggris",
    "features.guide.title": "Panduan Lokal",
    "features.guide.desc": "Temukan tempat tersembunyi dan restoran di Busan yang direkomendasikan oleh penduduk lokal",
    "features.map.title": "Peta Interaktif",
    "features.map.desc": "Jelajahi atraksi Busan secara visual dengan Google Maps",
    "community.title": "Komunitas",
    "community.subtitle": "Cerita dari para wisatawan",
    "community.write": "Tulis Posting",
    "community.category.all": "Semua",
    "community.category.review": "Ulasan Perjalanan",
    "community.category.question": "Pertanyaan",
    "community.category.tip": "Tips Perjalanan",
    "community.category.general": "Umum",
    "community.empty": "Belum ada posting. Jadilah yang pertama menulis!",
    "community.login_required": "Login diperlukan untuk menulis posting",
    "community.views": "Tampilan",
    "community.comments": "Komentar",
    "post.title": "Judul",
    "post.content": "Konten",
    "post.category": "Kategori",
    "post.language": "Bahasa Penulisan",
    "post.submit": "Posting",
    "post.cancel": "Batal",
    "post.translate": "Terjemahkan",
    "post.translating": "Menerjemahkan...",
    "post.translated": "Diterjemahkan",
    "post.original": "Lihat Asli",
    "post.comment.placeholder": "Tulis komentar...",
    "post.comment.submit": "Komentar",
    "post.comment.login": "Login diperlukan untuk berkomentar",
    "guide.title": "Panduan Lokal",
    "guide.subtitle": "Temukan permata tersembunyi Busan",
    "guide.category.all": "Semua",
    "guide.category.attraction": "Atraksi",
    "guide.category.restaurant": "Restoran",
    "guide.category.accommodation": "Akomodasi",
    "guide.category.shopping": "Belanja",
    "guide.category.culture": "Budaya",
    "guide.map_view": "Lihat di Peta",
    "map.title": "Peta Atraksi Busan",
    "map.subtitle": "Jelajahi atraksi Busan di peta",
    "profile.title": "Profil Saya",
    "profile.nickname": "Nama Panggilan",
    "profile.preferred_language": "Bahasa Pilihan",
    "profile.bio": "Bio",
    "profile.my_posts": "Posting Saya",
    "profile.save": "Simpan",
    "profile.saved": "Tersimpan",
    "common.loading": "Memuat...",
    "common.error": "Terjadi kesalahan",
    "common.back": "Kembali",
    "common.more": "Lihat Lebih Banyak",
    "common.close": "Tutup",
    "common.by": "Oleh",
    "common.ago": "lalu",
    "common.login_to_continue": "Masuk untuk melanjutkan",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("busanconnect_lang");
    const lang = (stored as Language) || "ko";
    // 유효한 언어인지 확인
    return LANGUAGES.some(l => l.code === lang) ? lang : "ko";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("busanconnect_lang", lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      // 현재 언어 번역이 없으면 한국어로 폴백
      return translations[language]?.[key] || translations["ko"]?.[key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

// 새 언어 추가 가이드:
// 1. Language 타입에 언어 코드 추가 (예: "th")
// 2. LANGUAGES 배열에 언어 정보 추가
// 3. translations 객체에 언어별 번역 추가
